[supervisord]
nodaemon=true
user=root

[program:shairport-sync]
command=/usr/bin/shairport-sync -a "Mony" --output=alsa -- -d hw:1,0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:librespot]
command=/usr/bin/librespot --name "Mony" --device hw:1,0 --bitrate 160 --backend alsa --disable-audio-cache
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
