[supervisord]
nodaemon=true
user=root

[program:dbus]
command=/usr/bin/dbus-daemon --system --nofork
priority=1
autorestart=true

[program:avahi]
command=/usr/sbin/avahi-daemon --no-drop-root
priority=2
autorestart=true

[program:shairport-sync]
command=/usr/bin/shairport-sync -a "Mony" --output=alsa -- -d hw:1,0
priority=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:librespot]
command=/usr/bin/librespot --name "Mony" --device hw:1,0 --bitrate 160 --backend alsa --disable-audio-cache
priority=4
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
